### ISSUE TITLE
CutMix on detection

### ISSUE THREAD

**Issue by wtupc96** [clovaai/CutMix-PyTorch#19]
Hi, thanks for your great job!
I have a question about applying CutMix on detection tasks.
Can I just use CutMix on detection datasets like coco, if I can, should I choose objects from the same image to paste or those in the same batch? :)

**Comment by hellbell** [comment]
@wtupc96 
Our paper only shows the effectiveness of `CutMix-pretrained model` when it is used as a pretrained backbone for object detection. 
In fact, we didn't try to directly apply CutMix for object detection like coco dataset, because, as you know, CutMix on the detection dataset is not straightforward (the discontinuity on the boundary may raise problems..)
