### ISSUE TITLE
Question About CutMix

### ISSUE THREAD

**Issue by SyGoing** [clovaai/CutMix-PyTorch#22]
If in the mini batch random sampling, when the sample pairs combine new data, image a and image B are background regions in the clipping region, and the background regions are almost similar, rather than the region where the target is located, is it reasonable to train the forced model fitting?

**Comment by hellbell** [comment]
@SyGoing 
As you pointed the new sample may have only background pixels and no objects since we crop random regions. But the background pixels are not useless but may contain useful information corresponding to their classes, so we guess this effect can enhance the image classification accuracy. 
(Similar question and answer #16)
